CREATE DATABASE IF NOT EXISTS kaeltitle CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS kaeltitle.player_titles (
    uuid CHAR(36) PRIMARY KEY,
    player_name VARCHAR(16) NOT NULL,
    title VARCHAR(16) NOT NULL DEFAULT '',
    nickname VARCHAR(16) NULL,
    last_nick_change BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
